for i in range(5):
    print("Hello World")
    print("Good morning")

for j in range(1, 11):
    print(j)
    print(j * 2)
    print(j * 3)
    print(j * 4)
    print(j * 5)
    print(j * 6)
    print(j * 7)
    print(j * 8)
    print(j * 9)
    print(j * 10)
    print(j * 11)
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")
    print("hello work")

